---

platform: linux

image_resource:
  type: docker-image
  source: {repository: pcfnorm/rootfs}

params:
  PRODUCT_SLUG:
  TARGET_VERSION:
  REVISIONS:
  IAAS_TYPE:
  API_TOKEN:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  S3_BUCKET_NAME:
  S3_ENDPOINT:
  SRT:

inputs:
  - name: offline-resources-repo

outputs:
  - name: pivnet-products
  - name: stemcells

run:
  path: offline-resources-repo/tasks/download-pivnet-products/task.sh